o sa mearga ce scriu aici
codetapacademy/html-css-javascript-starter pull request #154
Opened 2021-04-27 12:37 UTC by Nicolleta1981

2021-04-29 20:19 UTC, biggicode requested changes
In file names like ''value atribute.html'' you want to put ''-'' between words

2021-04-29 20:24 UTC, biggicode commented on web/nicolleta1981/html/Value attribute/value attribute.html
> +        <li>dialog-Use when the form is inside a < dialog > element to close the dialog when submitted.
you want to close dialog element

2021-04-29 20:24 UTC, biggicode commented on web/nicolleta1981/html/Value attribute/value attribute.html
> +          <p>This value can be overriden by a formmethod attribute on a < button >or < input >element.</p>
Button must be closed or deleted here ,on input you want to put atleast a "type" attribute

2021-04-29 22:12 UTC, vasilemaftita approved these changes
Nice; Work.

2021-04-30 06:50 UTC, vasilemaftita approved these changes
Nice; Work!

2021-04-30 20:50 UTC, screpyy96 approved these changes
💯

2021-04-30 23:12 UTC, vasilemaftita approved these changes
Nice; Work!

2021-05-01 02:19 UTC, psyhedeliq approved these changes

2021-05-01 06:42 UTC, Adrian01C reviewed
cool

2021-05-01 08:05 UTC, marianzburlea approved these changes

2021-05-01 08:59 UTC, marianzburlea approved these changes

2021-05-01 08:59 UTC, marianzburlea commented on web/nicolleta1981/css/font/font.html
> +<link rel="preconnect" href="https://fonts.gstatic.com">
baga-le in head

2021-05-01 08:59 UTC, merged

2021-05-01 12:36 UTC, vasilemaftita reviewed
Nice; Work...