2021 03 18 ralucarbc javascript some more methods and functions
codetapacademy/html-css-javascript-starter pull request #50
Opened 2021-03-18 22:47 UTC by RalucaRbc

this closes #47 
this closes #48 
this closes #49

2021-03-18 23:03 UTC, andreimaff approved these changes
niceee 💯

2021-03-18 23:10 UTC, Constantin-Matei approved these changes
Nice!✔

2021-03-18 23:19 UTC, M00N89 approved these changes
stupendo 💯

2021-03-19 04:05 UTC, QuintyHH commented on web/ralucarbc/javascript/all-unique/all-unique.js
> +  str.length === [...new Set(str.split(""))].length ? true : false;
By default returns boolean, no need to use ternary (you can safely remove ? true : false, the outcome doesn't change)

2021-03-19 04:13 UTC, QuintyHH commented on web/ralucarbc/javascript/squares-sequence/squares-sequence.js
> +}
This function could use a refactor, I suggest you use arrow functions, and replace the 'for' loop with a map. Also, declaring the array as a new instance of the Array class is VERY 1985.

Good use of guard clause on 18, but there is no need for an 'else' statement on 19, as that defeats the purpose of the early return.

2021-03-19 04:17 UTC, QuintyHH commented on web/ralucarbc/javascript/squares-sequence/squares-sequence.js
> +h2Instructions.textContent = `Complete the function that returns an array of length n, starting with the given number x and the squares of the previous number. If n is negative or zero, return an emp
I've seen this throughout your commits. The use of ticks (Template String) and concatenation as well. 
If ES6 is permitted, feel free to use just Template String (Ex: `This is my string bit to which I add my ${variable}`)
Else, use old school string concat (Ex: "This is my string to which I add my " + variable)

2021-03-19 04:18 UTC, QuintyHH requested changes
Sorry I have to do this to you, Raluca :)

2021-03-19 10:57 UTC, marianzburlea requested changes
for -> map
let's have a chat

2021-03-20 04:46 UTC, marianzburlea approved these changes
💯

2021-03-20 07:46 UTC, QuintyHH commented on web/ralucarbc/javascript/all-unique/all-unique.js
> +  str.length === [...new Set(str.split(""))].length;
no need to split, [...new Set(str)].length is enough

2021-03-20 07:50 UTC, QuintyHH requested changes
Final changes plix

2021-03-20 07:59 UTC, QuintyHH approved these changes

2021-03-20 08:00 UTC, merged