WIP: 2021 03 29 adrian01c htmt css clocking
codetapacademy/html-css-javascript-starter pull request #74
Opened 2021-03-29 11:07 UTC by Adrian01C

2021-04-03 06:54 UTC, adelacecilia commented
Consider re-doing the indentation :)

2021-04-03 06:55 UTC, adelacecilia reviewed
These look okay.

2021-04-03 07:29 UTC, vasilemaftita commented on web/adrian01c/classes/index.html
> +
please delete the empty line... no empty lines in HTML.

2021-04-03 07:29 UTC, vasilemaftita commented on web/adrian01c/classes/index.html
> +
please delete the empty line... no empty lines in HTML.

2021-04-03 07:30 UTC, vasilemaftita commented on web/adrian01c/classes/index.html
> +
please delete the empty line... no empty lines in HTML.

2021-04-03 07:35 UTC, vasilemaftita commented on web/adrian01c/classes/index.html
> +<head>
Please indent ` <head>` properly

2021-04-03 07:43 UTC, vasilemaftita commented on web/adrian01c/our-promise.html/about.html
> +</html>
you need a new line added at the end of HTML

2021-04-03 07:44 UTC, vasilemaftita submitted a review, later dismissed
you need a new line added at the end of HTML

2021-04-03 17:04 UTC, RadosavAntonio requested changes, later dismissed
I recommend a smaller indentation.
https://stackoverflow.com/questions/34174207/how-to-change-indentation-in-visual-studio-code 
Also please leave an empty line at the end of each file.

2021-04-05 13:09 UTC, QuintyHH approved these changes
Nice

2021-04-05 13:10 UTC, RalucaRbc approved these changes

2021-04-05 13:48 UTC, screpyy96 approved these changes
💯

2021-04-05 13:49 UTC, merged